### ISSUE TITLE
ParagraphStyle support?

### ISSUE THREAD

**Issue by matt-curtis** [kovpas/BOString#2]
`NSMutableParagraphStyle` support would be great, if possible

**Comment by kovpas** [comment]
Could you please clarify? You can set `NSParagraphStyleAttributeName` with [`paragraphStyle`](https://github.com/kovpas/BOString/blob/master/BOString/BOStringMaker.h#L317) method:

```
NSMutableParagraphStyle *ps = [[NSMutableParagraphStyle alloc] init];
ps.lineBreakMode = NSLineBreakByTruncatingMiddle;
NSAttributedString *result = [@"string" makeString:^(BOStringMaker *make) {
    make.paragraphStyle(ps);
}];
```

**Comment by matt-curtis** [comment]
Whoops, my mistake, I missed that! Sorry
